# Generated by Django 5.0.2 on 2024-02-29 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_game_collection_user_game_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='game_collection',
        ),
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/', verbose_name='Profile Picture'),
        ),
    ]
